caddyperf:
1. which implementation typo
2. position to which() moved to top
3. vim magic line bottom
4. FORCE_WGET=1 FORCE_CURL=1 by default
5. name changed from performance-checker.sh
6. tried to fix a bug when $2 is unset; field <input> had to be set for that server
7. one stop for mime-make-ing.

shutils/mime-make:

1. NOW it's mine.
2. NOW bc is not necessary.
3. randstr() is replaced so AWK replaces it.
4. TODO. replace AWK codes comparing to character code.

shutils/mktemp:

1. NOW it's mine.
2. NOW bc is not necessary.
3. random_string() is replaced so AWK replaces it.
4. replaced [ -n str ] || cmd and grep -q re && cmd with case statements

diff --git a/caddyperf b/caddyperf
--- a/caddyperf
+++ b/caddyperf
@@ -2,12 +2,15 @@
 
 ################################################################################
 #
-# performance-checker.sh
+# caddyperf
 # POST to http://golf.shinh.org/checker.rb with program source and input file.
 #
-# first commit.
+# 1. FORCE_WGET=1 FORCE_CURL=1 by default
+# 2. name changed from performance-checker.sh
+# 3. tried to fix a bug when $2 is unset; field <input> had to be set for that server
+# 4. one stop for mime-make-ing.
 #
-# written by Tpaefawzen on 2022-07-03
+# written by Tpaefawzen on 2022-07-15
 #
 ################################################################################
 
@@ -33,60 +36,66 @@ export PATH="$(command -p getconf PATH)${PATH+:}${PATH-:}"
 export UNIX_STD=2003
 export POSIXLY_CORRECT=1
 
+# hi utilities
+error_exit(){
+   echo "${0##*/}: $2" 1>&2
+   exit "$1"
+}
+type which >/dev/null 2>&1 || {
+   which(){
+      command -v "$1" 2>/dev/null | grep '^/' || {
+         echo 'which: not found' 1>&2
+         (exit 1)
+      }
+   }
+}
+
+# port from shinh/caddy/caddy
 case "$0" in (*/*)
-	export SRC_DIR="${0%/*}"
+   export SRC_DIR="${0%/*}"
 ;;(*)
-	# no slashes; invoking from somewhere on ${PATH}?
-	export SRC_DIR="$(which "$0")"
+   # no slashes; invoking from somewhere on ${PATH}?
+   export SRC_DIR="$(which "$0")"
 esac
 
 # let me think of utilities
 export PATH="$SRC_DIR/shutils:$PATH"
 
-# hi utility
-error_exit(){
-	echo "${0##*/}: $2" 1>&2
-	exit "$1"
-}
-type which >/dev/null 2>&1 || {
-  which(){
-	command -v "$1" 2>/dev/null | grep '^/' || {		
-		echo 'which: not found' 1>&2 &&
-		(exit 1)
-  }
-}
-
 # wget or curl?
+case "${FORCE_WGET:-}${FORCE_CURL:-}" in ('')
+   export FORCE_WGET=1 FORCE_CURL=1
+esac
+
+set +e
 case "${FORCE_WGET:-}" in (?*)
-	CMD_WGET="$(which wget)"
+   CMD_WGET="$(which wget 2>/dev/null)"
 esac
 
 case "${FORCE_CURL:-}" in (?*)
-	CMD_CURL="$(which curl)"
+   CMD_CURL="$(which curl 2>/dev/null)"
 esac
+set -e
 
-case "${CMD_WGET:-}${CMD_CURL:-}" in ('')
-	if type wget >/dev/null 2>&1; then
-		CMD_WGET="$(which wget)"
-	elif type curl >/dev/null 2>&1; then
-		CMD_CURL="$(which curl)"
-	else
-		error_exit 1 "wget or curl required"
-	fi
+case "${CMD_WGET:-}${FORCE_CURL:-}" in ('')
+   error_exit 1 'wget/curl is required'
 esac
 
 usage(){
-	cat <<-USAGE 1>&2
-	Usage: [env [FORCE_WGET=1|FORCE_CURL=1]] ${0##*/} SOURCE_PATH [INPUT_PATH]
+   cat <<-USAGE 1>&2
+	Usage: ${0##*/} SOURCE_PATH [INPUT_PATH]
+	Environment variables:
+	  FORCE_WGET
+	  FORCE_CURL
+	    Set unnull to enable.
 	USAGE
-	exit $1
+   exit $1
 }
 
 # parse options!
 case "$#" in (1|2)
-	:
+   :
 ;;(*)
-	usage 1
+   usage 1
 esac
 
 # main!
@@ -100,23 +109,25 @@ exit_trap() {
 trap 'exit_trap' EXIT HUP INT QUIT PIPE ALRM TERM
 Tmp=`mktemp -d -t "_${0##*/}.$$.XXXXXXXXXXX"` || error_exit 1 'Failed to mktemp'
 
-URL=http://golf.shinh.org/checker.rb
+URL='http://golf.shinh.org/checker.rb'
 
 s="$(mime-make -m)"
 content_type='Content-type: multipart/form-data; boundary="'$s'"'
 
-mime-make -b "$s" -F file "$1" ${2:+-F input "$2"} |
-if test "${CMD_WGET:-}"; then
-	cat >"$Tmp/mimedata"
-	"$CMD_WGET" -q -O - \
-		--header="$content_type" \
-		--post-file="$Tmp/mimedata" \
-		"$URL"
-elif test "${CMD_CURL:-}"; then
-	"$CMD_CURL" -s \
-		-H "$content_type" \
-		--data-binary @- \
-		"$URL"
-fi
+mime-make -b "$s" -F file "$1" -F input "${2:-/dev/null}" >"$Tmp/mimedata"
+
+case "${CMD_WGET:+wget}${CMD_CURL:+curl}" in (wget|wgetcurl)
+   "$CMD_WGET" -q -O - \
+      --header="$content_type" \
+      --post-file="$Tmp/mimedata" \
+      "$URL"
+;;(curl)
+   "$CMD_CURL" -s \
+      -H "$content_type" \
+      --data-binary @"$Tmp/mimedata" \
+      "$URL"
+;;esac
 
 exit_trap 0
+
+# vim: set softtabstop=3
